### ISSUE TITLE
Nitai's Comments

### ISSUE THREAD

**Issue by nitaiaharoni1** [rouih/crypto-kings#1]
Hi Itay,
Thanks for completing the assignment.
Please see my comments.

1. Please run lint to check for errors and fix them.

2. Run the formatter to keep the code style consistent.

3. Remove the `crypto-kings` service since it’s no longer needed.

4. It doesn’t seem necessary to have an interface for the `IBalanceController` controller. If this interface is only used in one app, there's no need to put it in the shared libraries.

5. It would be helpful to make a shared decorator for `@UserId`.

6. Improve DTO validation in the controllers by using `class-validator` and `class-transformer`—this is the recommended way to handle DTO validation in NestJS.

7. Use `POST /balances` and `PUT /balances/:asset` instead of `/balances/add` and `/balances/remove` because the HTTP methods already describe the action.

8. Use `PUT` instead of `DELETE` for balance deductions since you’re updating the amount instead of removing a record.

9. Just use `GET /balances`—there’s no need for both `/balances` and `/balances/userBalance`.

10. The current error handling treats all errors as "internal server errors," which makes it hard to distinguish user mistakes (like bad input) from real system issues (like database crashes). It’s better to give more specific error messages to help both users and developers.

11. `libs/shared/entities/balance.entity.ts` is only used by the balance service but is currently in shared libraries, and the same applies to the balance interfaces. Consider moving them out of shared.

12. The `libs/error-handling/exceptions` folder is at the root level of the shared library, unlike other shared modules, which are under `src`. Move it to `src` for consistency.

13. `crypto-kings/libs/shared/src/types/balance.type.ts` and `libs/shared/src/shared.service.ts` are empty files. Please remove them or fill them in.

14. The shared module should wrap all shared sub-modules like cache, logger, and file, making it easier to import what’s needed.

15. Adding a config module would help. Right now, environment variables are accessed directly in services—use `ConfigService` consistently instead.

16. The project’s logging setup needs improvement. The Winston logger in `winston-logger.ts` is basic. Consider adding things like request ID tracking, using proper log levels for different environments, and a more organized logging format. It would also help to set up a proper Logger module with dependency injection.

17. In `rate.service.ts`, the CronJob for updating rates could fail without anyone knowing. Add error handling and a retry mechanism for better reliability.

18. Test coverage is minimal—you need more integration and end-to-end tests, especially for error scenarios.

19. The `rebalance` endpoint doesn’t handle transactions well, meaning if one operation fails, others could still go through. Add proper transaction handling to make sure all operations are either completed or rolled back.

20. The balance operations don’t handle decimal precision properly. You should use a library like `decimal.js` to make sure calculations are accurate.
Let me know if this works for you or if you need anything else simplified or clarified!

**Comment by rouih** [comment]
Updated a new version :)
